<a href="https://colab.research.google.com/github/ryaltic/LCS-Predictions-2026/blob/main/LCS_Data_Collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import requests

headers = {"User-Agent": "Mozilla/5.0"}
all_matches = []

urls = [
    "https://gol.gg/game/stats/73776/page-fullstats/",
    "https://gol.gg/game/stats/73777/page-fullstats/"
]

def pull_match(url, match_id, game_num):

    response = requests.get(url, headers=headers)
    tables = pd.read_html(response.text)

    df = tables[0]

    # Clean table
    df = df.set_index(df.columns[0]).T.reset_index(drop=True)
    df.columns.name = None
    df.index.name = None

    # Add metadata
    df["MatchID"] = match_id
    df["Game"] = game_num

    return df

In [20]:
for i, url in enumerate(urls):
    try:
        match_df = pull_match(
            url=url,
            match_id=i,
            game_num=i + 1
        )
        all_matches.append(match_df)
    except Exception as e:
        print(f"Error pulling match {i}: {e}")

# Combine everything
final_df = pd.concat(all_matches, ignore_index=True)

print(final_df.head())
print(final_df.shape)

/tmp/ipython-input-3648557887.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)
/tmp/ipython-input-3648557887.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

      Player     Role Level Kills Deaths Assists KDA   CS CS in Team's Jungle  \
0     Morgan      TOP    17     3      1       2   5  257                   4
1  Josedeodo   JUNGLE    15     4      1       7  11  210                 185
2       Quid      MID    18     2      1       5   7  298                  12
3       Yeon      ADC    14     2      1       7   9  274                   4
4     CoreJJ  SUPPORT    13     0      1      10  10   23                   0

  CS in Enemy Jungle  ... Time ccing others Total Time CC Dealt  \
0                NaN  ...                 7                 161
1                NaN  ...                13                 542
2                NaN  ...                13                  47
3                NaN  ...                 4                  45
4                NaN  ...                16                 229

  Total damage taken Total Time Spent Dead Consumables purchased  \
0              16980                    37                     6
1              23862                    46                    10
2              18117                    25                     7
3              22055                    36                     5
4               6989                    12                    14

  Items Purchased Shutdown bounty collected Shutdown bounty lost MatchID Game
0              21                         0                    0       0    1
1              30                        89                  589       0    1
2              25                         0                    0       0    1
3              29                         0                   38       0    1
4              32                         0                    0       0    1

[5 rows x 58 columns]
(40, 58)

In [21]:
final_df.head(n=20)

,Player,Role,Level,Kills,Deaths,Assists,KDA,CS,CS in Team's Jungle,CS in Enemy Jungle,...,Time ccing others,Total Time CC Dealt,Total damage taken,Total Time Spent Dead,Consumables purchased,Items Purchased,Shutdown bounty collected,Shutdown bounty lost,MatchID,Game
0,Morgan,TOP,17,3,1,2,5,257,4,NaN,...,7,161,16980,37,6,21,0,0,0,1
1,Josedeodo,JUNGLE,15,4,1,7,11,210,185,NaN,...,13,542,23862,46,10,30,89,589,0,1
2,Quid,MID,18,2,1,5,7,298,12,NaN,...,13,47,18117,25,7,25,0,0,0,1
3,Yeon,ADC,14,2,1,7,9,274,4,NaN,...,4,45,22055,36,5,29,0,38,0,1
4,CoreJJ,SUPPORT,13,0,1,10,10,23,0,NaN,...,16,229,6989,12,14,32,0,0,0,1
5,Fudge,TOP,16,1,2,2,1.5,245,0,NaN,...,13,312,17264,37,6,22,0,89,0,1
6,Contractz,JUNGLE,14,1,2,1,1,209,195,NaN,...,12,310,20961,39,10,26,589,0,0,1
7,Zinie,MID,17,2,3,1,1,289,4,NaN,...,38,1320,24818,65,11,28,38,0,0,1
8,Bvoy,ADC,13,1,2,1,1,256,4,NaN,...,0,1,19201,39,2,24,0,0,0,1
9,Ceos,SUPPORT,11,0,2,3,1.5,32,0,NaN,...,15,79,8547,34,10,26,0,0,0,1
10,Morgan,TOP,16,1,1,2,3,264,0,NaN,...,17,144,22237,44,6,22,0,209,1,2
11,Josedeodo,JUNGLE,15,3,0,11,Perfect KDA,191,181,NaN,...,99,470,23532,0,8,26,0,0,1,2
12,Quid,MID,15,9,1,5,14,249,5,NaN,...,20,181,10669,0,3,23,0,700,1,2
13,Yeon,ADC,14,3,1,6,9,235,8,NaN,...,4,115,13279,25,3,17,0,0,1,2
14,CoreJJ,SUPPORT,11,1,0,13,Perfect KDA,24,0,NaN,...,33,136,8376,0,14,26,0,0,1,2
15,Fudge,TOP,15,2,3,0,0.7,225,0,NaN,...,16,317,16820,63,1,20,909,0,1,2
16,Contractz,JUNGLE,13,0,4,1,0.3,165,154,NaN,...,7,169,20495,148,8,25,0,0,1,2
17,Zinie,MID,13,0,6,0,0,225,0,NaN,...,5,117,18637,170,6,19,0,0,1,2
18,Bvoy,ADC,13,1,2,1,1,219,0,NaN,...,4,6,12304,67,3,20,0,0,1,2
19,Ceos,SUPPORT,9,0,2,2,1,30,0,NaN,...,12,42,15674,46,8,22,0,0,1,2

In [16]:
df.columns

Index(['Player', 'Role', 'Level', 'Kills', 'Deaths', 'Assists', 'KDA', 'CS',
       'CS in Team's Jungle', 'CS in Enemy Jungle', 'CSM', 'Golds', 'GPM',
       'GOLD%', 'Vision Score', 'Wards placed', 'Wards destroyed',
       'Control Wards Purchased', 'Detector Wards Placed', 'VSPM', 'WPM',
       'VWPM', 'WCPM', 'VS%', 'Total damage to Champion', 'Physical Damage',
       'Magic Damage', 'True Damage', 'DPM', 'DMG%', 'K+A Per Minute', 'KP%',
       'Solo kills', 'Double kills', 'Triple kills', 'Quadra kills',
       'Penta kills', 'GD@15', 'CSD@15', 'XPD@15', 'LVLD@15',
       'Objectives Stolen', 'Damage dealt to turrets',
       'Damage dealt to buildings', 'Total heal', 'Total Heals On Teammates',
       'Damage self mitigated', 'Total Damage Shielded On Teammates',
       'Time ccing others', 'Total Time CC Dealt', 'Total damage taken',
       'Total Time Spent Dead', 'Consumables purchased', 'Items Purchased',
       'Shutdown bounty collected', 'Shutdown bounty lost', 'MatchID', 'Game'],
      dtype='object')

In [15]:
df.head(n=20)

,Player,Role,Level,Kills,Deaths,Assists,KDA,CS,CS in Team's Jungle,CS in Enemy Jungle,...,Time ccing others,Total Time CC Dealt,Total damage taken,Total Time Spent Dead,Consumables purchased,Items Purchased,Shutdown bounty collected,Shutdown bounty lost,MatchID,Game
0,Morgan,TOP,17,3,1,2,5,257,4,NaN,...,7,161,16980,37,6,21,0,0,0,1
1,Josedeodo,JUNGLE,15,4,1,7,11,210,185,NaN,...,13,542,23862,46,10,30,89,589,0,1
2,Quid,MID,18,2,1,5,7,298,12,NaN,...,13,47,18117,25,7,25,0,0,0,1
3,Yeon,ADC,14,2,1,7,9,274,4,NaN,...,4,45,22055,36,5,29,0,38,0,1
4,CoreJJ,SUPPORT,13,0,1,10,10,23,0,NaN,...,16,229,6989,12,14,32,0,0,0,1
5,Fudge,TOP,16,1,2,2,1.5,245,0,NaN,...,13,312,17264,37,6,22,0,89,0,1
6,Contractz,JUNGLE,14,1,2,1,1,209,195,NaN,...,12,310,20961,39,10,26,589,0,0,1
7,Zinie,MID,17,2,3,1,1,289,4,NaN,...,38,1320,24818,65,11,28,38,0,0,1
8,Bvoy,ADC,13,1,2,1,1,256,4,NaN,...,0,1,19201,39,2,24,0,0,0,1
9,Ceos,SUPPORT,11,0,2,3,1.5,32,0,NaN,...,15,79,8547,34,10,26,0,0,0,1

In [25]:
import pandas as pd
import requests

headers = {"User-Agent": "Mozilla/5.0"}

url = "https://gol.gg/teams/team-matchlist/2812/split-Winter/tournament-ALL/"

response = requests.get(url, headers=headers)
tables = pd.read_html(response.text)

print(f"Total tables found: {len(tables)}")

for i, table in enumerate(tables):
    print(f"\n--- Table {i} ---")
    print(table.head())

Total tables found: 2

--- Table 0 ---
        0    1           2       3
0  Split:  ALL  Pre-Season  Winter

--- Table 1 ---
  C9 Result Score  Side  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6   Vs  \
0       WIN   3-0   NaN          24        56.2           7           3  FLY
1       WIN     |   NaN          12        55.6           9           2  FLY
2       WIN     |   NaN          18        62.7          10           4  FLY
3       WIN   2-1   NaN          26        57.9          11           4  FLY
4      LOSS     |   NaN           6        71.5          10           1  FLY

   Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11 Duration  \
0           9        46.2            2            1    25:46
1           5        44.1            3            2    25:37
2           4        49.7            1            0    29:02
3           5        40.1            0            0    24:39
4          13        73.6            7            5    38:44

                     Game  Patch             Week        Tournament
0  Cloud9 vs FlyQuest (3)   16.3  PLAYOFFS.ROUND1  LCS 2026 Lock-In
1  Cloud9 vs FlyQuest (2)   16.3  PLAYOFFS.ROUND1  LCS 2026 Lock-In
2  Cloud9 vs FlyQuest (1)   16.3  PLAYOFFS.ROUND1  LCS 2026 Lock-In
3  Cloud9 vs FlyQuest (3)   16.3     SWISS.ROUND3  LCS 2026 Lock-In
4  Cloud9 vs FlyQuest (2)   16.3     SWISS.ROUND3  LCS 2026 Lock-In

/tmp/ipython-input-186388516.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

In [31]:
cloud9_df = tables[1]
cloud9_df.rename(columns={"Unnamed: 3": "Teams Kill", "Unnamed: 4": "Teams Gold", "Unnamed: 5": "Teams Towers Taken", "Unnamed: 6": "Teams Dragons Taken",
                          "Unnamed: 8": "Opponents Kill", "Unnamed: 9": "Opponents Gold", "Unnamed: 10": "Opponents Towers Taken", "Unnamed: 11": "Opponents Dragons Taken",
                          "C9 Result": "Result"}, inplace=True)
cloud9_df['Team'] = "Cloud 9"

In [32]:
cloud9_df

,Result,Score,Side,Teams Kill,Teams Gold,Teams Towers Taken,Teams Dragons Taken,Vs,Opponents Kill,Opponents Gold,Opponents Towers Taken,Opponents Dragons Taken,Duration,Game,Patch,Week,Tournament,Team
0,WIN,3-0,NaN,24,56.2,7,3,FLY,9,46.2,2,1,25:46,Cloud9 vs FlyQuest (3),16.3,PLAYOFFS.ROUND1,LCS 2026 Lock-In,Cloud 9
1,WIN,|,NaN,12,55.6,9,2,FLY,5,44.1,3,2,25:37,Cloud9 vs FlyQuest (2),16.3,PLAYOFFS.ROUND1,LCS 2026 Lock-In,Cloud 9
2,WIN,|,NaN,18,62.7,10,4,FLY,4,49.7,1,0,29:02,Cloud9 vs FlyQuest (1),16.3,PLAYOFFS.ROUND1,LCS 2026 Lock-In,Cloud 9
3,WIN,2-1,NaN,26,57.9,11,4,FLY,5,40.1,0,0,24:39,Cloud9 vs FlyQuest (3),16.3,SWISS.ROUND3,LCS 2026 Lock-In,Cloud 9
4,LOSS,|,NaN,6,71.5,10,1,FLY,13,73.6,7,5,38:44,Cloud9 vs FlyQuest (2),16.3,SWISS.ROUND3,LCS 2026 Lock-In,Cloud 9
5,WIN,|,NaN,16,66.6,11,3,FLY,5,49.7,0,1,28:55,Cloud9 vs FlyQuest (1),16.3,SWISS.ROUND3,LCS 2026 Lock-In,Cloud 9
6,WIN,2-0,NaN,14,72.0,10,4,LYON,9,70.3,5,1,37:20,Cloud9 vs LYON (2),16.2,SWISS.ROUND2,LCS 2026 Lock-In,Cloud 9
7,WIN,|,NaN,8,84.0,7,4,LYON,13,83.3,6,3,45:20,Cloud9 vs LYON (1),16.2,SWISS.ROUND2,LCS 2026 Lock-In,Cloud 9
8,WIN,2-0,NaN,19,63.6,10,4,TLAW,4,49.4,2,1,30:33,Cloud9 vs Team Liquid (2),16.2,SWISS.ROUND1,LCS 2026 Lock-In,Cloud 9
9,WIN,|,NaN,13,70.4,8,2,TLAW,7,62.8,3,3,36:03,Cloud9 vs Team Liquid (1),16.2,SWISS.ROUND1,LCS 2026 Lock-In,Cloud 9